### ISSUE TITLE
Check Digit

### ISSUE THREAD

**Issue by voxsar** [slwdc/NICParser#2]
The last number in the new NIC and the last NUMBER in the nic (ignore the last letter) are check digits, is it possible to validate against this check digit as well, what is the check digit algorithm?
I checked with  Luhn algorithm, Verhoeff algorithm and Damm algorithm no one of them seem to generate the correct check digit for any nic

**Comment by Ayesh** [comment]
All the sources I could find only mentions that it is a check digit, but don't go as far to explain how the check is made. If someone knows, I'd be happy to roll out.

**Comment by Ayesh** [comment]
I'll close this issue because we couldn't come up with the check digit information. Please feel free to reopen if there's an interest.
